### ISSUE TITLE
Exported AnnData lacks genes in the rownames (at least when read by python)

### ISSUE THREAD

**Issue by bbimber** [mojaveazure/seurat-disk#105]
I'm trying to debug a pretty new issue that might be related to seurat-disk. We have R code that takes a SeruatObject and uses convert() in a basic way like:
```
SeuratDisk::Convert(source = h5seurat, dest = "h5ad", overwrite = T)
```

That is then read in python using scanpy:
```
import scanpy as sc
# These are the gene names (at least that's how celltypist, the python program we're running, reads them):
sc.read('seuratAnnData').var_names;
```
Up until a fairly recent change in some software package, this worked fine. However, starting within the last week or so, the rownames of the imported AnnData object are now numeric (0-n), instead of string GeneIds. It seems like perhaps seurat-disk isnt properly setting rownames in the exported file? Granted, this could be a change in scanpy or whatever python code is actually reading the AnnDisk file too.

Have you seen any issues like this before, or are you aware of changes in seurat-disk that might contribute to this?

Thanks for any ideas.

**Comment by bbimber** [comment]
this appears to be something related to python's anndata 0.8.0, and worked correctly with anndata 0.7.8:

https://github.com/theislab/anndata/issues/747

**Comment by ivirshup** [comment]
It looks like the files being written only have encoding metadata on `obs` and not `var`, so are off-spec in a way that we didn't check for previously. See https://github.com/theislab/anndata/issues/747#issuecomment-1082091818 for more details.

I think that this library should be putting `encoding-type` and `encoding-version` fields in `var` as well as `obs`, which should solve this issue.

**Comment by bbimber** [comment]
@ivirshup To clarify: you believe that seurat-disk should be altering the metadata in the anndata they create? 

My understanding of the guts of h5 files isnt great, but based on that issue, does this seem to be where seurat-disk needs to be setting encoding-type?

https://github.com/mojaveazure/seurat-disk/blob/163f1aade5bac38ed1e9e9c912283a7e74781610/R/Convert.R#L1056

and then maybe this needs to add encoding-type as an attribute, similar to what it's doing on line 1081 for column-order?

**Comment by bbimber** [comment]
@ivirshup Thanks for the pointer. We're using seurat-disk to write the annfile and passing this to an external python tool (celltypist). We dont have much control over how it's being read there. Their code is doing a basic sc.read(annFile). 

I'll write PR for seurat-disk and see if they'll accept the change. This seems easiest.

**Comment by bbimber** [comment]
@ivirshup Thanks for the quick help. I think this PR accomplishes this:

https://github.com/mojaveazure/seurat-disk/pull/106/files

**Comment by ivirshup** [comment]
I think this works with [MuDataSeurat](https://github.com/pmbio/MuDataSeurat) at the moment.

E.g.

```r
library(MuDataSeurat)

WriteH5AD(seuratObj, "obj.h5ad")
```
