### ISSUE TITLE
Conversion scrambles barcodes w/r/t metadata columns

### ISSUE THREAD

**Issue by aseyedia** [mojaveazure/seurat-disk#127]
I am trying to convert a Seurat object whose metadata I've edited to h5ad for use with cellxgene. The Seurat object itself produces a normal UMAP within R: 

![image](https://user-images.githubusercontent.com/43455034/186925438-436428eb-f50a-4388-ae90-df2d5f8be95d.png)

But once I convert it to `h5Seurat` and then to `h5ad`, it gets scrambled along the way:

```
SaveH5Seurat(
  rpca_umap,
  filename = "processed/02-annotation/rpca_umap.h5Seurat",
  verbose = TRUE,
  overwrite = TRUE
)

Convert(
  source = "processed/02-annotation/rpca_umap.h5Seurat",
  dest = "h5ad",
  assay = "RNA",
  verbose = TRUE,
  overwrite = TRUE
)
```

![image](https://user-images.githubusercontent.com/43455034/186925713-ea6ed951-59b4-46c2-a407-c94d4bf0a8bb.png)

If I load the h5ad into Python, I can clearly see that metadata columns become reordered in their relation to the index, because I stored the barcodes into a column early into processing, and they no longer match up:

```python
>>> scrna.obs['orig.bc']
AAACCCACAAGGCTTT-1_1     AAACCCAAGACCATAA-1_2
AAACCCAGTTGCCAAT-1_1     AAACCCAAGACCATTC-1_6
AAACCCATCCAGCACG-1_1     AAACCCAAGAGTGTGC-1_6
AAACCCATCGACATAC-1_1     AAACCCAAGCCTATCA-1_6
AAACCCATCGATACAC-1_1     AAACCCAAGCCTCAAT-1_3
                                 ...         
TTTGTCAAGAGGGCTT-1_12    TTTGTTGTCATCTATC-1_5
TTTGTCAAGGCGCTCT-1_12    TTTGTTGTCCGGACTG-1_6
TTTGTCAAGGGCTTGA-1_12    TTTGTTGTCGCAGTCG-1_4
TTTGTCAAGTCCGTAT-1_12    TTTGTTGTCGGTCTGG-1_2
TTTGTCACATTGGTAC-1_12    TTTGTTGTCGTACCTC-1_1
Name: orig.bc, Length: 69179, dtype: object
```

But I don't know why.

I have spent hours poking and prodding this file in different ways to see what the issue is. I've tried converting different assays, different ways of editing the metadata, loading the h5ad into Python to examine the object. None of this seems to work. So now I'm at a complete loss. Let me know if you have any ideas.

**Comment by aseyedia** [comment]
Just found out that this was because the order of the meta data columns in Seurat was different from the order of `Seurat::Cells`, and somewhere along the conversion process, SeuratDisk assumes that the order of the meta data columns **is** the order of the barcodes of the UMAP coordinates.

**Comment by dustin-mullaney** [comment]
Hi, I am currently having this same issue. Can you provide more detail on how you solved it?

**Comment by aseyedia** [comment]
Make sure the order of the columns are the same as the order of the cell barcodes. You can use [`Seurat::RenameCells`](https://satijalab.org/seurat/reference/renamecells) to accomplish this. However, this was over a year ago, so I don't really remember.
