### ISSUE TITLE
LoadH5Seurat no longer working for me

### ISSUE THREAD

**Issue by ccnawrocki** [mojaveazure/seurat-disk#156]
Hello, 
I have had this Seurat object for about a year, and I have not been having any problems until now. Suddenly, when I try to use `LoadH5Seurat` I am getting an error that I do not understand. 

```
library(Seurat)
library(SeuratDisk)

DATA <- LoadH5Seurat("/Users/cnawrocki/Library/CloudStorage/OneDrive-UniversityofVirginia/Grainger Lab/Bioinformatics/Data/Seurat Objects/PC30_cellxgene.h5Seurat")
```

I get the following:

```
> library(Seurat)
> library(SeuratDisk)
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat
> DATA <- LoadH5Seurat("/Users/cnawrocki/Library/CloudStorage/OneDrive-UniversityofVirginia/Grainger Lab/Bioinformatics/Data/Seurat Objects/PC30_cellxgene.h5Seurat")
Validating h5Seurat file
Initializing RNA with data
Adding counts for RNA
Adding scale.data for RNA
Adding feature-level metadata for RNA
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”
> 
```

I am using a 2020 M1 MacBook Air, MacOS Ventura 13.4, R 4.3.0, Seurat 4.3.0.1, SeuratDisk 0.0.0.9020. 

I would appreciate any help.

**Comment by stefanonard85** [comment]
I get the same identic error.

**Comment by Sophia409** [comment]
I also get the same error. How did you solve it?

**Comment by ccnawrocki** [comment]
@stefanonard85 @Sophia409 After much investigation, I have figured it out. The issue is that Seurat v5 uses a new version of the Seurat object. If you do the following, it should work: 
```
remove.packages("Seurat") 
remove.packages("SeuratObject")
```

Restart your R session. If you are using RStudio, you can do:
```
.rs.restartR()
```

Lastly, reinstall the correct version of R. 
```
install.packages("Seurat", version="4.3.0.1")
library(Seurat)
library(SeuratDisk)
```

Once, you have done this, it ought to work. Definitely am going to look into virtual environments with R to keep my SeuratObject versions separate. 

Hope that this helps.

**Comment by mschilli87** [comment]
I guess you could also convert your Seurat object to a SingleCellExperiment and save that to an Rds file or export your object to a loom/H5 file directly using the old version (just install it into a separate library path that you specifiy manually while loading, if required), switch to the new version (in a new R session) and read the file back into the new Seurat object format. I am still on 4.x but that would be my update strategy for projects that I don't want/can't re-run the entire (new) workflow.

**Comment by oligoelemento** [comment]
Identical error and what I did to solve it (probably the install order could vary but this worked for me):
`remove.packages(c('Seurat','SeuratData','SeuratDisk','SeuratObject','SeuratWrappers'))
remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet=F)
remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet=F)
remotes::install_github("satijalab/seurat", "seurat5", quiet=F)
remotes::install_github("satijalab/seurat-data", "seurat5", quiet=F)
remotes::install_github("mojaveazure/seurat-disk", quiet=F)`

**Comment by ccnawrocki** [comment]
Just thought I would say here that Seurat seems to have fixed this issue. When you have Seurat v5 installed, you can switch between object types by doing: 
```
options(Seurat.object.assay.version = "v3") 
```
for the older objects. 

Conversely, you can do: 
```
options(Seurat.object.assay.version = "v5") 
```
for the new objects. 

Additionally, the SeuratDisk functions seem to work with Seurat v5 now. 

Closing the issue.
