### ISSUE TITLE
Convert do not allow multiple assays to be converted at a time for use with scVelo as demonstrated in scVelo vignette

### ISSUE THREAD

**Issue by saeedfc** [mojaveazure/seurat-disk#21]
Hi,

I am following the scVelo vignette (in seuratwrappers) with the following seurat Object. After creating h5ad file and importing it as an anndata object, it seems that, assays other than RNA is not written to h5ad. If I use assays argument in Convert function, it only allows one assay, not multiple assays. Can you help me solve this? Thanks in advance!

>Fib
An object of class Seurat 
152625 features across 13143 samples within 6 assays 
Active assay: RNA (25697 features, 0 variable features)
 5 other assays present: SCT, integrated, spliced, unspliced, ambiguous
 4 dimensional reductions calculated: pca, umap, harm_umap, harmony

**In R**

```
>DefaultAssay(Fib) <- "RNA"

>SaveH5Seurat(Fib, filename = "Fibroblast_for_scVelo_complete.h5Seurat")
Creating h5Seurat file for version 3.1.2
Adding counts for RNA
Adding data for RNA
No variable features found for RNA
No feature-level metadata found for RNA
Adding counts for SCT
Adding data for SCT
Adding scale.data for SCT
No variable features found for SCT
No feature-level metadata found for SCT
Adding data for integrated
Adding scale.data for integrated
Adding variable features for integrated
No feature-level metadata found for integrated
Adding counts for spliced
Adding data for spliced
No variable features found for spliced
No feature-level metadata found for spliced
Adding counts for unspliced
Adding data for unspliced
No variable features found for unspliced
No feature-level metadata found for unspliced
Adding counts for ambiguous
Adding data for ambiguous
No variable features found for ambiguous
No feature-level metadata found for ambiguous
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
Adding cell embeddings for harm_umap
No loadings for harm_umap
No projected loadings for harm_umap
No standard deviations for harm_umap
No JackStraw data for harm_umap
Adding cell embeddings for harmony
No loadings for harmony
No projected loadings for harmony
No standard deviations for harmony
No JackStraw data for harmony

>Convert("Fibroblast_for_scVelo_complete.h5Seurat", dest = "h5ad")
Validating h5Seurat file
Adding data from RNA as X
Adding counts from RNA as raw
Transfering meta.data to obs
Adding dimensional reduction information for umap (global)

```
**In python**

```
import scvelo as scv
adata = scv.read("/mnt/DATA1/Fibrosis/Full Scale Analysis/scVelo/Fibroblast_integrated_for_scVelo_complete.h5ad")
adata
Out[8]: 
AnnData object with n_obs × n_vars = 13143 × 25697 
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'GC_Sample_Number', 'Location', 'Segment', 'Patient_Type', 'Biopsy_method', 'Age', 'Patient_no', 'Sample', 'Sample_type', 'Gender', 'percent.mt', 'nCount_SCT', 'nFeature_SCT', 'integrated_snn_res.2', 'seurat_clusters', 'Harmony_Clusters', 'integrated_snn_res.1', 'integrated_snn_res.0.6', 'integrated_snn_res.0.4', 'integrated_snn_res.0.3', 'integrated_snn_res.0.2', 'integrated_snn_res.0.15', 'subtype', 'colors', 'nCount_spliced', 'nFeature_spliced', 'nCount_unspliced', 'nFeature_unspliced', 'nCount_ambiguous', 'nFeature_ambiguous', 'initial_size'
    var: 'features'
    obsm: 'X_umap'
```
notice that var: only shows 'features' as opposed to var: 'features', 'ambiguous_features', 'spliced_features', 'unspliced_features' shown in the vignette (below is how it is in the vignette) and the layers are not added.

```
 AnnData object with n_obs × n_vars = 6667 × 24421
    obs: 'orig.ident', 'nCount_spliced', 'nFeature_spliced', 'nCount_unspliced', 'nFeature_unspliced', 'nCount_ambiguous', 'nFeature_ambiguous', 'nCount_RNA', 'nFeature_RNA', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.0.8', 'seurat_clusters'
    var: 'features', 'ambiguous_features', 'spliced_features', 'unspliced_features'
    obsm: 'X_umap'
    layers: 'ambiguous', 'spliced', 'unspliced'
```

**Comment by saeedfc** [comment]
Hi,

In the help page of Convert it is clearly mentioned that for an assay to be written to layers, it should have the same shape as the assay which is written as X for the anndata. It turns out that my spliced, unspliced etc assays were not of the same shape as RNA data slot which was written as X. 

The processed RNA (data slot) assay had only 25697 genes (during preprocessing, genes that were not at all expressed were removed). However the spliced, unspliced and ambiguous assays had counts slots with 30k+ genes* n cells matrices. So the shape is not same as RNA data slot which is written as X for the anndata object. So if I first subset the assays with the extra genes to contain only the same genes as in X(aka RNA data slot) it should work

```
genes_in _use <- rownames(GetAssayData(Fib, assay = "RNA", slot = "data")),] 

spliced <- GetAssayData(SO_merged, assay = "spliced") %>% .[rownames(.) %in% genes_in_use,] %>% CreateAssayObject()
unspliced <- GetAssayData(SO_merged, assay = "unspliced") %>% .[rownames(.) %in% genes_in_use,] %>% CreateAssayObject()
ambiguous <- GetAssayData(SO_merged, assay = "ambiguous") %>% .[rownames(.) %in% genes_in_use,] %>% CreateAssayObject()


Fib[["spliced"]] <- spliced
Fib[["unspliced"]] <- unspliced
Fib[["ambiguous"]] <- ambiguous

> DefaultAssay(Fib) <- "RNA"
> SaveH5Seurat(Fib, filename = "Fibroblast_scvelo.h5Seurat")
Creating h5Seurat file for version 3.1.2
Adding counts for RNA
Adding data for RNA
Adding variable features for RNA
Adding feature-level metadata for RNA
Adding counts for SCT
Adding data for SCT
Adding scale.data for SCT
No variable features found for SCT
No feature-level metadata found for SCT
Adding data for integrated
Adding scale.data for integrated
Adding variable features for integrated
Adding feature-level metadata for integrated
Adding counts for spliced
Adding data for spliced
No variable features found for spliced
No feature-level metadata found for spliced
Adding counts for unspliced
Adding data for unspliced
No variable features found for unspliced
No feature-level metadata found for unspliced
Adding counts for ambiguous
Adding data for ambiguous
No variable features found for ambiguous
No feature-level metadata found for ambiguous
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
Adding cell embeddings for harm_umap
No loadings for harm_umap
No projected loadings for harm_umap
No standard deviations for harm_umap
No JackStraw data for harm_umap
Adding cell embeddings for harmony
No loadings for harmony
No projected loadings for harmony
No standard deviations for harmony
No JackStraw data for harmony
> Convert("Fibroblast_scvelo.h5Seurat", dest = "h5ad", overwrite =T)
Validating h5Seurat file
Adding data from RNA as X
Transfering meta.features to var
Adding counts from RNA as raw
Transfering meta.features to raw/var
Transfering meta.data to obs
Adding dimensional reduction information for umap (global)
Adding data from ambiguous as a layer
Adding data from spliced as a layer
Adding data from unspliced as a layer
```

**Comment by tiramisutes** [comment]
Hi,
In my Seurat object, there has the same shape as the RNA assay. But still, no spliced, unspliced etc assays were added to the layer when run Convert.
```
> sc_seurat
An object of class Seurat 
190128 features across 30631 samples within 4 assays 
Active assay: RNA (47532 features, 3000 variable features)
 3 other assays present: spliced, unspliced, ambiguous
 3 dimensional reductions calculated: pca, tsne, umap
```
```
> dim(sc_seurat@assays$ambiguous@data)
[1] 47532 30631
> dim(sc_seurat@assays$unspliced@data)
[1] 47532 30631
> dim(sc_seurat@assays$spliced@data)
[1] 47532 30631
> dim(sc_seurat@assays$RNA@data)
[1] 47532 30631
```
```
> SaveH5Seurat(sc_seurat, filename = "sc_seurat.h5Seurat")
Creating h5Seurat file for version 3.1.5.9900
Adding counts for RNA
Adding data for RNA
Adding scale.data for RNA
Adding variable features for RNA
Adding feature-level metadata for RNA
Adding counts for spliced
Adding data for spliced
Adding scale.data for spliced
No variable features found for spliced
No feature-level metadata found for spliced
Adding counts for unspliced
Adding data for unspliced
No variable features found for unspliced
No feature-level metadata found for unspliced
Adding counts for ambiguous
Adding data for ambiguous
No variable features found for ambiguous
No feature-level metadata found for ambiguous
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for tsne
No loadings for tsne
No projected loadings for tsne
No standard deviations for tsne
No JackStraw data for tsne
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
> Convert("sc_seurat.h5Seurat", dest = "h5ad", overwrite =T)
Validating h5Seurat file
Adding scale.data from RNA as X
Transfering meta.features to var
Adding data from RNA as raw
Transfering meta.features to raw/var
Transfering meta.data to obs
Adding dimensional reduction information for pca
Adding feature loadings for pca
Adding dimensional reduction information for tsne
Adding dimensional reduction information for umap
Adding RNA_snn as neighbors
```

**Comment by MikaQiao** [comment]
@tiramisutes 
Hi,
I run into the same issues with you. I've checked the structure, and found that the `RNA` assay has a slot `scale.data`, but the `spliced` slot does not. So, I solved by 
```
sc_seurat@assays$RNA@scale.data <- sc_seurat@assays$spliced@scale.data

```

hope this helps you.

**Comment by chitcode** [comment]
If data from other slots is to be exported such as 'data', then the following workaround works

```
sc_seurat@assays$RNA@scale.data <- as.matrix(sc_seurat@assays$spliced@data)

```

**Comment by ctlshcxy** [comment]
> Hi, In my Seurat object, there has the same shape as the RNA assay. But still, no spliced, unspliced etc assays were added to the layer when run Convert.
> 
> ```
> > sc_seurat
> An object of class Seurat 
> 190128 features across 30631 samples within 4 assays 
> Active assay: RNA (47532 features, 3000 variable features)
>  3 other assays present: spliced, unspliced, ambiguous
>  3 dimensional reductions calculated: pca, tsne, umap
> ```
> 
> ```
> > dim(sc_seurat@assays$ambiguous@data)
> [1] 47532 30631
> > dim(sc_seurat@assays$unspliced@data)
> [1] 47532 30631
> > dim(sc_seurat@assays$spliced@data)
> [1] 47532 30631
> > dim(sc_seurat@assays$RNA@data)
> [1] 47532 30631
> ```
> 
> ```
> > SaveH5Seurat(sc_seurat, filename = "sc_seurat.h5Seurat")
> Creating h5Seurat file for version 3.1.5.9900
> Adding counts for RNA
> Adding data for RNA
> Adding scale.data for RNA
> Adding variable features for RNA
> Adding feature-level metadata for RNA
> Adding counts for spliced
> Adding data for spliced
> Adding scale.data for spliced
> No variable features found for spliced
> No feature-level metadata found for spliced
> Adding counts for unspliced
> Adding data for unspliced
> No variable features found for unspliced
> No feature-level metadata found for unspliced
> Adding counts for ambiguous
> Adding data for ambiguous
> No variable features found for ambiguous
> No feature-level metadata found for ambiguous
> Adding cell embeddings for pca
> Adding loadings for pca
> No projected loadings for pca
> Adding standard deviations for pca
> No JackStraw data for pca
> Adding cell embeddings for tsne
> No loadings for tsne
> No projected loadings for tsne
> No standard deviations for tsne
> No JackStraw data for tsne
> Adding cell embeddings for umap
> No loadings for umap
> No projected loadings for umap
> No standard deviations for umap
> No JackStraw data for umap
> > Convert("sc_seurat.h5Seurat", dest = "h5ad", overwrite =T)
> Validating h5Seurat file
> Adding scale.data from RNA as X
> Transfering meta.features to var
> Adding data from RNA as raw
> Transfering meta.features to raw/var
> Transfering meta.data to obs
> Adding dimensional reduction information for pca
> Adding feature loadings for pca
> Adding dimensional reduction information for tsne
> Adding dimensional reduction information for umap
> Adding RNA_snn as neighbors
> ```

seems that you don't have SCT assay in your Seurat object.
