### ISSUE TITLE
Error in Graphs(object = x) : could not find function "Graphs"

### ISSUE THREAD

**Issue by grimwoo** [mojaveazure/seurat-disk#52]
When I want to save seurat.object to loom file, I encountered this error:

```
> object.loom <- as.loom(object, filename = 'neurons.loom', verbose = T)
Saving data from RNA as /matrix
  |===========================================================| 100%
Adding slot counts for assay RNA
Adding layer counts
  |===========================================================| 100%
Adding slot scale.data for assay RNA
Adding layer scale.data
Error in Graphs(object = x) : could not find function "Graphs"
```

The code performed well on previous version of seurat. However, the new seurat required SeuratDisk. Even I checked all the [dependencies listed](https://github.com/mojaveazure/seurat-disk), I still got this error.

**Comment by grimwoo** [comment]
This error could be figured out by import library ```library(SeuratObject)```

**Comment by kmshort** [comment]
Yeah, this is a problem that should be addressed with a decent error. I found the same issue as you. Miffed that Seurat just can't do it on its own.
