### ISSUE TITLE
pbmc_multimodal.h5seurat error when loading

### ISSUE THREAD

**Issue by JLTrincado** [mojaveazure/seurat-disk#66]
Dear authors,

congrats on the last release, it's amazing.

I'm trying to load the dataset you generated on Hao and Hao: https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat

When loading the object I receive the following error:

```
> pbmc.Hao <- LoadH5Seurat(file="/scratch/devel/jtrincado/scCART/misc/pbmc_multimodal.h5seurat")
Validating h5Seurat file
Initializing ADT with data
Adding counts for ADT
Adding variable feature information for ADT
Adding miscellaneous information for ADT
Initializing SCT with data
Adding counts for SCT
Adding variable feature information for SCT
Adding miscellaneous information for SCT
Found more than one class "Assay" in cache; using the first, from namespace 'Seurat'
Also defined by ‘SeuratObject’
Found more than one class "Assay" in cache; using the first, from namespace 'Seurat'
Also defined by ‘SeuratObject’
Error in .getClassesFromCache(Class) : 
  class should be either a character-string name or a class definition
```

I checked for this error in previous issues but I haven't found anyone with the same problem. What am I doing wwong?

Thanks again.
Best,

Juan Luis.

**Comment by messersc** [comment]
I have the same problem on a fresh install.

**Comment by JLTrincado** [comment]
Hi @messersc ,

yes you're right. Updating to V4 works fine.

Thanks for your help.
