### ISSUE TITLE
Problems in finding the cell and feature metadata

### ISSUE THREAD

**Issue by ensiferum877** [mojaveazure/seurat-disk#8]
Hi guys,

I tried to use the convert() function to read H5AD files into Seurat. This worked to some extent. However, after running convert( ), I noticed the following warnings.

Convert("/Users/felipe/adatabeta_seurat.h5ad", dest = "h5seurat", overwrite = TRUE)

**Warning: Unknown file type: h5ad**
Warning: 'assay' not set, setting to 'RNA'
Creating h5Seurat file for version 3.1.2
Adding X as data
Adding X as counts
**Warning: Cannot yet add feature-level metadata from compound datasets
Warning: No cell-level metadata present, creating fake cell names**
Adding X_diffmap as cell embeddings for diffmap
Adding X_draw_graph_fa as cell embeddings for draw_graph_fa
Adding X_pca as cell embeddings for pca
Adding X_tsne as cell embeddings for tsne
Adding X_umap as cell embeddings for umap
Adding PCs as feature loadings fpr pca
Adding Treatment_categories to miscellaneous data
Adding batch_categories to miscellaneous data
Adding louvain_final_categories to miscellaneous data
Adding louvain_r0.0195_categories to miscellaneous data
Adding phase_categories to miscellaneous data
Adding layer counts as data in assay counts
Adding layer counts as counts in assay counts

Then, I loaded the created seurat object in R. After inspecting the data, I noticed that the feature and cell metadata were not imported. However, all the dimensionality reductions and count matrix were properly imported.

The h5ad file was produced as follows:

A loom file was generated in python using scanpy==1.5.1 anndata==0.7.3 and h5py ==2.10.0
Then, in a different environment with scanpy==1.4.4.post1 anndata==0.6.22.post1 and h5py==2.9.0, I finally produced the h5ad file.

It did not make any difference whether adata.X was sparse or whether I stored adata.raw.X as sparse and adata.X as dense.

Could be that I am failing to import all the data because the h5ad file was produced in an older scanpy and anndata version ?

Best,

Felipe

**Comment by ensiferum877** [comment]
Hi guys,

Quick answer: I manage to solve the problem by creating an H5AD file using scanpy==1.5.1 anndata==0.7.3 and h5py ==2.10.0. 
Before writing the H5AD file, I transformed the adata.X to sparse and then moved to the adata.raw. Then, everything worked well.

Best,

Felipe

**Comment by mojaveazure** [comment]
Hi Felipe,

We target anndata/H5AD 0.7.X in our converters. For future reference, you can easily update an older H5AD file to a newer one by reading the data in and writing it back out using a new version of anndata (>= 0.70).

Glad you got it figured out!
