### ISSUE TITLE
C stack usage error during SaveH5Seurat call

### ISSUE THREAD

**Issue by alexthiery** [mojaveazure/seurat-disk#88]
Hi. I am regularly converting from seurat to h5ad and occasionally encountering issues with function recursion.

I am just trying to do a simple h5ad to h5Seurat conversion but get the following C stack error. Has anyone else encountered this? Any help would be much appreciated!

```R
SaveH5Seurat(seurat_object, filename = paste0(opt$outfile, '.h5Seurat'))
```

Error:
```R
Creating h5Seurat file for version 3.1.5.9900
Adding data for integrated
Adding variable features for integrated
No feature-level metadata found for integrated
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
Error: C stack usage  7970324 is too close to the limit
```

**Comment by alexthiery** [comment]
I seemed to have resolved this for now. Depending on the contents of `seurat@misc`, you may encounter recursion errors during the h5Seurat conversion. In order to get around this simply reset the misc slot before converting.

```R
seurat@misc <- list()
```

**Comment by listen2099** [comment]
@alexthiery Love you, baby
